CREATE TABLE IF NOT EXISTS app_data (
  id INT PRIMARY KEY,
  data JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO app_data (id, data)
VALUES (1, JSON_OBJECT())
ON DUPLICATE KEY UPDATE id = id;
